import type { CurrentScan } from '../types/rf';
import type { SchedulerDecision } from '../types/scheduler';


export interface DemoStep {
  stepIndex: number;
  timeSlot: number;
  scan: CurrentScan;
  decision: SchedulerDecision;
  narrative: string;
}

export const DEMO_SCRIPT_STEPS: DemoStep[] = [
  {
    stepIndex: 1,
    timeSlot: 101,
    scan: {
      time_slot: 101,
      frequency_band: 1,
      signal_power: -0.32,
      pulse_width: 0.0,
      angle_of_arrival: null,
      detector_prediction: false,
      detector_state: 'INACTIVE',
      result: 'MISS',
      reward: -0.1,
    },
    decision: {
      next_band: 2,
      estimated_hit_probability: 0.05,
      exploration_probability: 1.0,
      strategy: 'EXPLORATION',
      reasoning: 'Baseline open-loop sweep scanning Band 2 next in fixed sequential order.',
      band_probabilities: [
        { band: 7, probability: 0.15, recent_scans: 0, recent_hits: 0 },
        { band: 3, probability: 0.10, recent_scans: 0, recent_hits: 0 },
        { band: 1, probability: 0.05, recent_scans: 1, recent_hits: 0 },
        { band: 2, probability: 0.05, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 1: Traditional blind sweep starts on Band 1. No emitter present (Power -0.32 dB) -> MISS (-0.1 reward).',
  },
  {
    stepIndex: 2,
    timeSlot: 102,
    scan: {
      time_slot: 102,
      frequency_band: 2,
      signal_power: 0.45,
      pulse_width: 0.0,
      angle_of_arrival: null,
      detector_prediction: false,
      detector_state: 'INACTIVE',
      result: 'MISS',
      reward: -0.1,
    },
    decision: {
      next_band: 7,
      estimated_hit_probability: 0.35,
      exploration_probability: 0.20,
      strategy: 'EXPLORATION',
      reasoning: 'Adaptive Exploration: Model initiates intelligent probe across high-entropy Band 7.',
      band_probabilities: [
        { band: 7, probability: 0.35, recent_scans: 0, recent_hits: 0 },
        { band: 3, probability: 0.20, recent_scans: 0, recent_hits: 0 },
        { band: 2, probability: 0.05, recent_scans: 1, recent_hits: 0 },
        { band: 1, probability: 0.05, recent_scans: 1, recent_hits: 0 },
      ],
    },
    narrative: 'Step 2: Sequential scan on Band 2 yields noise MISS. Adaptive scheduler overrides sequence to probe Band 7.',
  },
  {
    stepIndex: 3,
    timeSlot: 103,
    scan: {
      time_slot: 103,
      frequency_band: 7,
      signal_power: 9.42,
      pulse_width: 1.85,
      angle_of_arrival: 42.1,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 7,
      estimated_hit_probability: 0.78,
      exploration_probability: 0.20,
      strategy: 'EXPLOITATION',
      reasoning: 'Active emitter discovered on Band 7 with 9.42 dB SNR. Exploit high-value emitter burst.',
      band_probabilities: [
        { band: 7, probability: 0.78, recent_scans: 1, recent_hits: 1 },
        { band: 3, probability: 0.25, recent_scans: 0, recent_hits: 0 },
        { band: 9, probability: 0.20, recent_scans: 0, recent_hits: 0 },
        { band: 12, probability: 0.15, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 3: High-power pulsed radar intercepted on Band 7! Detector triggers ACTIVE (9.42 dB), Evaluator confirms HIT (+1.0 reward).',
  },
  {
    stepIndex: 4,
    timeSlot: 104,
    scan: {
      time_slot: 104,
      frequency_band: 7,
      signal_power: 8.85,
      pulse_width: 1.62,
      angle_of_arrival: 41.9,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 3,
      estimated_hit_probability: 0.45,
      exploration_probability: 0.20,
      strategy: 'EXPLORATION',
      reasoning: 'Band 7 sustained. Model explores secondary candidate Band 3 to detect multi-emitter agility.',
      band_probabilities: [
        { band: 7, probability: 0.84, recent_scans: 2, recent_hits: 2 },
        { band: 3, probability: 0.45, recent_scans: 0, recent_hits: 0 },
        { band: 9, probability: 0.25, recent_scans: 0, recent_hits: 0 },
        { band: 12, probability: 0.15, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 4: Model exploits Band 7 again (HIT +1.0). With Band 7 locked, ε-scheduler probes Band 3.',
  },
  {
    stepIndex: 5,
    timeSlot: 105,
    scan: {
      time_slot: 105,
      frequency_band: 3,
      signal_power: 8.15,
      pulse_width: 2.10,
      angle_of_arrival: 54.2,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 7,
      estimated_hit_probability: 0.88,
      exploration_probability: 0.20,
      strategy: 'EXPLOITATION',
      reasoning: 'Secondary emitter detected on Band 3 (8.15 dB). Re-prioritizing top active emitters on Bands 7 & 3.',
      band_probabilities: [
        { band: 7, probability: 0.88, recent_scans: 2, recent_hits: 2 },
        { band: 3, probability: 0.72, recent_scans: 1, recent_hits: 1 },
        { band: 9, probability: 0.30, recent_scans: 0, recent_hits: 0 },
        { band: 18, probability: 0.18, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 5: Secondary threat discovered on Band 3 (AoA 54.2°)! Second HIT (+1.0 reward).',
  },
  {
    stepIndex: 6,
    timeSlot: 106,
    scan: {
      time_slot: 106,
      frequency_band: 7,
      signal_power: 9.10,
      pulse_width: 1.75,
      angle_of_arrival: 42.0,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 3,
      estimated_hit_probability: 0.75,
      exploration_probability: 0.20,
      strategy: 'EXPLOITATION',
      reasoning: 'Interleaved exploitation: Alternating between confirmed active emitters on Bands 7 and 3.',
      band_probabilities: [
        { band: 7, probability: 0.90, recent_scans: 3, recent_hits: 3 },
        { band: 3, probability: 0.75, recent_scans: 1, recent_hits: 1 },
        { band: 9, probability: 0.32, recent_scans: 0, recent_hits: 0 },
        { band: 12, probability: 0.20, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 6: Smart scheduler locks onto interleaved dwell schedule between Band 7 & Band 3, maximizing intercept throughput.',
  },
  {
    stepIndex: 7,
    timeSlot: 107,
    scan: {
      time_slot: 107,
      frequency_band: 3,
      signal_power: 7.95,
      pulse_width: 1.95,
      angle_of_arrival: 54.0,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 12,
      estimated_hit_probability: 0.38,
      exploration_probability: 0.20,
      strategy: 'EXPLORATION',
      reasoning: 'Exploration interval: Probing Band 12 to maintain whole-spectrum vigilance against agile hoppers.',
      band_probabilities: [
        { band: 7, probability: 0.91, recent_scans: 3, recent_hits: 3 },
        { band: 3, probability: 0.82, recent_scans: 2, recent_hits: 2 },
        { band: 12, probability: 0.38, recent_scans: 0, recent_hits: 0 },
        { band: 9, probability: 0.30, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 7: Band 3 hit confirmed (+1.0 reward). Exploration interval triggered to maintain whole-spectrum situational awareness.',
  },
  {
    stepIndex: 8,
    timeSlot: 108,
    scan: {
      time_slot: 108,
      frequency_band: 12,
      signal_power: 1.15,
      pulse_width: 0.0,
      angle_of_arrival: null,
      detector_prediction: false,
      detector_state: 'INACTIVE',
      result: 'MISS',
      reward: -0.1,
    },
    decision: {
      next_band: 7,
      estimated_hit_probability: 0.92,
      exploration_probability: 0.20,
      strategy: 'EXPLOITATION',
      reasoning: 'Band 12 quiet. Immediately snapping back to high-yield emitter on Band 7.',
      band_probabilities: [
        { band: 7, probability: 0.92, recent_scans: 3, recent_hits: 3 },
        { band: 3, probability: 0.80, recent_scans: 2, recent_hits: 2 },
        { band: 9, probability: 0.28, recent_scans: 0, recent_hits: 0 },
        { band: 12, probability: 0.12, recent_scans: 1, recent_hits: 0 },
      ],
    },
    narrative: 'Step 8: Band 12 scan yields noise. Scheduler immediately snaps back to proven threat on Band 7 rather than wasting energy sweeping.',
  },
  {
    stepIndex: 9,
    timeSlot: 109,
    scan: {
      time_slot: 109,
      frequency_band: 7,
      signal_power: 8.72,
      pulse_width: 1.43,
      angle_of_arrival: 42.1,
      detector_prediction: true,
      detector_state: 'ACTIVE',
      result: 'HIT',
      reward: 1.0,
    },
    decision: {
      next_band: 3,
      estimated_hit_probability: 0.85,
      exploration_probability: 0.20,
      strategy: 'EXPLOITATION',
      reasoning: 'Continuous high reward achieved (+5.6 cumulative). Dual-emitter tracking operating at peak intercept efficiency.',
      band_probabilities: [
        { band: 7, probability: 0.94, recent_scans: 4, recent_hits: 4 },
        { band: 3, probability: 0.85, recent_scans: 2, recent_hits: 2 },
        { band: 9, probability: 0.25, recent_scans: 0, recent_hits: 0 },
        { band: 18, probability: 0.15, recent_scans: 0, recent_hits: 0 },
      ],
    },
    narrative: 'Step 9: Re-intercept on Band 7 (+1.0 reward). Adaptive scanning delivers 70%+ energy efficiency over fixed sweeping.',
  },
];
